version: '3.9'

services:
  redis:
    restart: always
    image: redis
    expose:
      - '6379'
  
  app:
    restart: always
    build: ./
    expose:
      - '8080'
    links:
      - redis

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - '80:80'
    links:
      - app
